### ISSUE TITLE
Misunderstood .gitignore?

### ISSUE THREAD

**Issue by szabgab** [x-lamprocapnos-x/Movie-Selector#1]
Hi,
it seems there is a misunderstand how `.gitignore` works. It should be a file that includes the patterns you would like to exclude. This repo now contains all the files that are inside the `.gitignore` folder. See [this post](https://dev.to/szabgab/billions-of-unnecessary-files-in-github-i85) for more details.

If you are interested I can send a Pull-Request fixing this though it will not remove the content of the `.gitignore` folder from the history of this repo.

**Comment by x-lamprocapnos-x** [comment]
Thank you so much for this! I appreciate your input immensely. The link you attached was very helpful! I believe I am using .gitignore correctly now!

**Comment by szabgab** [comment]
The file you added is called `gitignore` it should be called `.gitignore` with a leading dot.
You also need to remove the `node_modules` folder so:

```
git rm node_modules
git commit -m "remove generated files"
git mv gitignore .gitignore
git commit -m "rename gitignore"
```

Then you can install the npm packages again.

**Comment by x-lamprocapnos-x** [comment]
I appreciate your help, thank you so much!

**Comment by szabgab** [comment]
hi @x-lamprocapnos-x 
I received a lot of value from the time and energy people put in various open source projects. Opening this issue was my way of passing on a tiny bit of good deed to someone else. I am trying now to invite more people, you too, to find other project(s) and make a small contribution there. See this issue explaining my reasoning further: https://github.com/OSDC-Code-Maven/OSDC-Code-Maven.github.io/issues/5
